blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/Societe-tangeroise-de-maintenance/GitArena/discussions
    about: Use Discussions for questions, ideas, and show-and-tell.
